/* automatically generated by rust-bindgen 0.71.1 */

/* OS: unix */
/* Platform: aarch64-apple-darwin20 */
/* rustc 1.85.0 (4d91de4e4 2025-02-17) */
/* R version: 4.3.3 */

unsafe extern "C" {
    pub fn R_FlushConsole();
    #[doc = " always declared, but only usable under Win32 and Aqua"]
    pub fn R_ProcessEvents();
}
