/* automatically generated by rust-bindgen 0.71.1 */

/* OS: unix */
/* Platform: x86_64-pc-linux-gnu */
/* rustc 1.85.0 (4d91de4e4 2025-02-17) */
/* R version: 4.4.3 */

pub const __STDC_WANT_IEC_60559_FUNCS_EXT__: u32 = 1;
unsafe extern "C" {
    pub fn R_FlushConsole();
    #[doc = " always declared, but only usable under Win32 and Aqua"]
    pub fn R_ProcessEvents();
}
