/* automatically generated by rust-bindgen 0.71.1 */

/* OS: windows */
/* Platform:  */
/* rustc 1.85.1 (4eb161250 2025-03-15) */
/* R version: 4.6.0 */

pub const __STDC_WANT_IEC_60559_FUNCS_EXT__ : u32 = 1 ; unsafe extern "C" { pub fn R_FlushConsole () ; # [doc = " always declared, but only usable under Win32 and Aqua"] pub fn R_ProcessEvents () ; pub fn R_WaitEvent () ; }