/* automatically generated by rust-bindgen 0.72.0 */

/* OS: windows */
/* Platform:  */
/* rustc 1.91.1 (ed61e7d7e 2025-11-07) */
/* R version: 4.5.2 */

unsafe extern "C" {
    pub fn R_FlushConsole();
    #[doc = " always declared, but only usable under Win32 and Aqua"]
    pub fn R_ProcessEvents();
    pub fn R_WaitEvent();
}
