/* automatically generated by rust-bindgen 0.72.0 */

/* OS: windows */
/* Platform:  */
/* rustc 1.91.1 (ed61e7d7e 2025-11-07) */
/* R version: 4.5.2 */

pub const HAVE_F77_UNDERSCORE: u32 = 1;
pub const IEEE_754: u32 = 1;
pub const SUPPORT_UTF8: u32 = 1;
pub const SUPPORT_MBCS: u32 = 1;
pub const ENABLE_NLS: u32 = 1;
pub const PR18534fixed: u32 = 1;
pub const SIZEOF_SIZE_T: u32 = 8;
pub const HAVE_UINTPTR_T: u32 = 1;
pub const HAVE_ENUM_BASE_TYPE: u32 = 1;
