/* automatically generated by rust-bindgen 0.71.1 */

/* OS: unix */
/* Platform: aarch64-apple-darwin20 */
/* rustc 1.85.0 (4d91de4e4 2025-02-17) */
/* R version: 4.3.3 */

pub type s_object = SEXPREC;
pub const TRUE: u32 = 1;
pub const FALSE: u32 = 0;
