/* automatically generated by rust-bindgen 0.72.0 */

/* OS: windows */
/* Platform:  */
/* rustc 1.91.0 (f8297e351 2025-10-28) */
/* R version: 4.5.2 */

pub type s_object = SEXPREC;
pub const TRUE: u32 = 1;
pub const FALSE: u32 = 0;
