/* automatically generated by rust-bindgen 0.71.1 */

/* OS: windows */
/* Platform:  */
/* rustc 1.85.1 (4eb161250 2025-03-15) */
/* R version: 4.4.3 */

pub const R_VERSION: u32 = 263171;
pub const R_NICK: &[u8; 12] = b"Trophy Case\0";
pub const R_MAJOR: &[u8; 2] = b"4\0";
pub const R_MINOR: &[u8; 4] = b"4.3\0";
pub const R_STATUS: &[u8; 1] = b"\0";
pub const R_YEAR: &[u8; 5] = b"2025\0";
pub const R_MONTH: &[u8; 3] = b"02\0";
pub const R_DAY: &[u8; 3] = b"28\0";
pub const R_SVN_REVISION: u32 = 87843;
