/* automatically generated by rust-bindgen 0.71.1 */

/* OS: windows */
/* Platform:  */
/* rustc 1.85.1 (4eb161250 2025-03-15) */
/* R version: 4.5.0 */

pub const R_VERSION: u32 = 263424;
pub const R_NICK: &[u8; 1] = b"\0";
pub const R_MAJOR: &[u8; 2] = b"4\0";
pub const R_MINOR: &[u8; 4] = b"5.0\0";
pub const R_STATUS: &[u8; 6] = b"alpha\0";
pub const R_YEAR: &[u8; 5] = b"2025\0";
pub const R_MONTH: &[u8; 3] = b"03\0";
pub const R_DAY: &[u8; 3] = b"24\0";
pub const R_SVN_REVISION: u32 = 88048;
