/* automatically generated by rust-bindgen 0.70.1 */

/* aarch64-apple-darwin20 */
/* rustc 1.81.0 (eeb90cda1 2024-09-04) */
/* r version: 4.4.1 */

pub const __STDC_WANT_IEC_60559_FUNCS_EXT__: u32 = 1;
extern "C" {
    pub fn R_FlushConsole();
    #[doc = " always declared, but only usable under Win32 and Aqua"]
    pub fn R_ProcessEvents();
}
