/* automatically generated by rust-bindgen 0.71.1 */

/* OS: unix */
/* Platform: aarch64-apple-darwin20 */
/* rustc 1.87.0-nightly (be73c1f46 2025-03-21) */
/* R version: 4.6.0 */

unsafe extern "C" {
    pub fn R_FlushConsole();
    #[doc = " always declared, but only usable under Win32 and Aqua"]
    pub fn R_ProcessEvents();
}
