/* automatically generated by rust-bindgen 0.70.1 */

/* aarch64-apple-darwin20 */
/* rustc 1.81.0 (eeb90cda1 2024-09-04) */
/* r version: 4.4.1 */

pub type s_object = SEXPREC;
pub const TRUE: u32 = 1;
pub const FALSE: u32 = 0;
