/* automatically generated by rust-bindgen 0.70.1 */

pub const Rboolean_FALSE: Rboolean = 0;
pub const Rboolean_TRUE: Rboolean = 1;
pub type Rboolean = ::std::os::raw::c_uint;
extern "C" {
    pub static mut R_Interactive: Rboolean;
    pub static mut R_NoEcho: Rboolean;
    pub fn R_RestoreGlobalEnv();
    pub fn R_RestoreGlobalEnvFromFile(arg1: *const ::std::os::raw::c_char, arg2: Rboolean);
    pub fn R_SaveGlobalEnv();
    pub fn R_SaveGlobalEnvToFile(arg1: *const ::std::os::raw::c_char);
    pub fn R_FlushConsole();
    pub fn R_ClearerrConsole();
    pub fn R_Suicide(arg1: *const ::std::os::raw::c_char);
    pub fn R_HomeDir() -> *mut ::std::os::raw::c_char;
    pub static mut R_DirtyImage: ::std::os::raw::c_int;
    pub static mut R_GUIType: *mut ::std::os::raw::c_char;
    pub fn R_setupHistory();
    pub static mut R_HistoryFile: *mut ::std::os::raw::c_char;
    pub static mut R_HistorySize: ::std::os::raw::c_int;
    pub static mut R_RestoreHistory: ::std::os::raw::c_int;
    pub static mut R_Home: *mut ::std::os::raw::c_char;
    pub fn Rf_jump_to_toplevel();
    pub fn Rf_mainloop();
    pub fn Rf_onintr();
    pub fn Rf_onintrNoResume();
    pub static mut R_GlobalContext: *mut ::std::os::raw::c_void;
    pub fn process_site_Renviron();
    pub fn process_system_Renviron();
    pub fn process_user_Renviron();
    pub static mut R_Consolefile: *mut FILE;
    pub static mut R_Outputfile: *mut FILE;
    pub fn R_setStartTime();
    pub fn fpu_setup(arg1: Rboolean);
    pub static mut R_running_as_main_program: ::std::os::raw::c_int;
    pub static mut R_SignalHandlers: ::std::os::raw::c_int;
}
