/* automatically generated by rust-bindgen 0.70.1 */

pub const R_VERSION: u32 = 263169;
pub const R_NICK: &[u8; 19] = b"Race for Your Life\0";
pub const R_MAJOR: &[u8; 2] = b"4\0";
pub const R_MINOR: &[u8; 4] = b"4.1\0";
pub const R_STATUS: &[u8; 1] = b"\0";
pub const R_YEAR: &[u8; 5] = b"2024\0";
pub const R_MONTH: &[u8; 3] = b"06\0";
pub const R_DAY: &[u8; 3] = b"14\0";
pub const R_SVN_REVISION: u32 = 86737;
