/* automatically generated by rust-bindgen 0.70.1 */

extern "C" {
    pub static mut R_NaN: f64;
    pub static mut R_PosInf: f64;
    pub static mut R_NegInf: f64;
    pub static mut R_NaReal: f64;
    pub static mut R_NaInt: ::std::os::raw::c_int;
    pub fn R_IsNA(arg1: f64) -> ::std::os::raw::c_int;
    pub fn R_IsNaN(arg1: f64) -> ::std::os::raw::c_int;
    pub fn R_finite(arg1: f64) -> ::std::os::raw::c_int;
}
