/* automatically generated by rust-bindgen 0.70.1 */

/* rustc 1.81.0 (eeb90cda1 2024-09-04) */
/* r version: 4.4.1 */

#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Rboolean {
    #[doc = ", MAYBE"]
    FALSE = 0,
    #[doc = ", MAYBE"]
    TRUE = 1,
}
