/* automatically generated by rust-bindgen 0.70.1 */

/* rustc 1.81.0 (eeb90cda1 2024-09-04) */
/* r version: 4.4.1 */

extern "C" {
    #[doc = " used by package tkrplot"]
    pub fn R_GetX11Image(
        d: ::std::os::raw::c_int,
        pximage: *mut ::std::os::raw::c_void,
        pwidth: *mut ::std::os::raw::c_int,
        pheight: *mut ::std::os::raw::c_int,
    ) -> Rboolean;
}
