/* automatically generated by rust-bindgen 0.70.1 */

extern "C" {
    #[doc = " used by package tkrplot"]
    pub fn R_GetX11Image(
        d: ::std::os::raw::c_int,
        pximage: *mut ::std::os::raw::c_void,
        pwidth: *mut ::std::os::raw::c_int,
        pheight: *mut ::std::os::raw::c_int,
    ) -> Rboolean;
}
