/* automatically generated by rust-bindgen 0.70.1 */

/* OS: unix */
/* Platform: aarch64-apple-darwin20 */
/* rustc 1.81.0 (eeb90cda1 2024-09-04) */
/* R version: 4.4.1 */

#[cfg(feature = "r_4_4_1")]
#[cfg(target_family = "unix")]
pub const GET_REGION_BUFSIZE: u32 = 512;
