/* automatically generated by rust-bindgen 0.70.1 */

/* OS: unix */
/* Platform: aarch64-apple-darwin20 */
/* rustc 1.81.0 (eeb90cda1 2024-09-04) */
/* R version: 4.4.1 */

extern "C" {
    #[cfg(feature = "r_4_4_1")]
    #[cfg(target_family = "unix")]
    #[doc = " S Like Memory Management"]
    pub fn R_chk_calloc(arg1: usize, arg2: usize) -> *mut ::std::os::raw::c_void;
    #[cfg(feature = "r_4_4_1")]
    #[cfg(target_family = "unix")]
    pub fn R_chk_realloc(
        arg1: *mut ::std::os::raw::c_void,
        arg2: usize,
    ) -> *mut ::std::os::raw::c_void;
    #[cfg(feature = "r_4_4_1")]
    #[cfg(target_family = "unix")]
    pub fn R_chk_free(arg1: *mut ::std::os::raw::c_void);
}
