// Auto-generated by tools/reduce_cached_bindings.py. Do not edit.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unused)]

#[cfg(any(
    all(target_os = "macos", r_ver_4_3),
    all(target_os = "macos", r_ver_4_4),
))]
include!("../libintl-Darwin-4.3.rs");

#[cfg(any(
    all(target_os = "windows", r_ver_4_3),
    all(target_os = "windows", r_ver_4_4),
    all(target_os = "windows", r_ver_4_5),
    all(target_os = "windows", r_ver_4_6),
))]
include!("../libintl-windows-4.3.rs");

#[cfg(not(any(
    all(target_os = "macos", r_ver_4_3),
    all(target_os = "macos", r_ver_4_4),
    all(target_os = "windows", r_ver_4_3),
    all(target_os = "windows", r_ver_4_4),
    all(target_os = "windows", r_ver_4_5),
    all(target_os = "windows", r_ver_4_6),
)))]
compile_error!("No cached binding match for libintl on this platform / R version");
