// Auto-generated by tools/reduce_cached_bindings.py. Do not edit.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unused)]

#[cfg(any(
    all(target_os = "macos", r_ver_4_3),
    all(target_os = "linux", r_ver_4_3),
    all(target_os = "windows", r_ver_4_3),
))]
include!("../Rversion-Darwin-4.3.rs");

#[cfg(any(
    all(target_os = "macos", r_ver_4_4),
    all(target_os = "linux", r_ver_4_4),
    all(target_os = "windows", r_ver_4_4),
))]
include!("../Rversion-Darwin-4.4.rs");

#[cfg(any(
    all(target_os = "macos", r_ver_4_5),
    all(target_os = "linux", r_ver_4_5),
))]
include!("../Rversion-Darwin-4.5.rs");

#[cfg(any(
    all(target_os = "macos", r_ver_4_6),
))]
include!("../Rversion-Darwin-4.6.rs");

#[cfg(any(
    all(target_os = "linux", r_ver_4_6),
))]
include!("../Rversion-Linux-4.6.rs");

#[cfg(any(
    all(target_os = "windows", r_ver_4_5),
))]
include!("../Rversion-windows-4.5.rs");

#[cfg(any(
    all(target_os = "windows", r_ver_4_6),
))]
include!("../Rversion-windows-4.6.rs");

#[cfg(not(any(
    all(target_os = "macos", r_ver_4_3),
    all(target_os = "linux", r_ver_4_3),
    all(target_os = "windows", r_ver_4_3),
    all(target_os = "macos", r_ver_4_4),
    all(target_os = "linux", r_ver_4_4),
    all(target_os = "windows", r_ver_4_4),
    all(target_os = "macos", r_ver_4_5),
    all(target_os = "linux", r_ver_4_5),
    all(target_os = "macos", r_ver_4_6),
    all(target_os = "linux", r_ver_4_6),
    all(target_os = "windows", r_ver_4_5),
    all(target_os = "windows", r_ver_4_6),
)))]
compile_error!("No cached binding match for Rversion on this platform / R version");
