/* automatically generated by rust-bindgen 0.72.0 */

/* OS: windows */
/* Platform:  */
/* rustc 1.91.1 (ed61e7d7e 2025-11-07) */
/* R version: 4.5.2 */

unsafe extern "C" {
    pub fn Rf_error(arg1: *const ::std::os::raw::c_char, ...) -> !;
    pub fn UNIMPLEMENTED(arg1: *const ::std::os::raw::c_char) -> !;
    pub fn WrongArgCount(arg1: *const ::std::os::raw::c_char) -> !;
    pub fn Rf_warning(arg1: *const ::std::os::raw::c_char, ...);
    pub fn R_ShowMessage(s: *const ::std::os::raw::c_char);
}
