/* automatically generated by rust-bindgen 0.71.1 */

/* OS: windows */
/* Platform:  */
/* rustc 1.85.1 (4eb161250 2025-03-15) */
/* R version: 4.4.3 */

unsafe extern "C" { pub fn Rf_error (arg1 : * const :: std :: os :: raw :: c_char , ...) -> ! ; pub fn UNIMPLEMENTED (arg1 : * const :: std :: os :: raw :: c_char) -> ! ; pub fn WrongArgCount (arg1 : * const :: std :: os :: raw :: c_char) -> ! ; pub fn Rf_warning (arg1 : * const :: std :: os :: raw :: c_char , ...) ; pub fn R_ShowMessage (s : * const :: std :: os :: raw :: c_char) ; }