/* automatically generated by rust-bindgen 0.71.1 */

/* OS: unix */
/* Platform: aarch64-apple-darwin20 */
/* rustc 1.85.0 (4d91de4e4 2025-02-17) */
/* R version: 4.4.3 */

unsafe extern "C" {
    #[doc = " used by package tkrplot"]
    pub fn R_GetX11Image(
        d: ::std::os::raw::c_int,
        pximage: *mut ::std::os::raw::c_void,
        pwidth: *mut ::std::os::raw::c_int,
        pheight: *mut ::std::os::raw::c_int,
    ) -> Rboolean;
}
> Rboolean;
}
