/* automatically generated by rust-bindgen 0.72.0 */

/* OS: windows */
/* Platform:  */
/* rustc 1.91.0 (f8297e351 2025-10-28) */
/* R version: 4.5.2 */

pub const GET_REGION_BUFSIZE: u32 = 512;
