/* automatically generated by rust-bindgen 0.71.1 */

/* OS: unix */
/* Platform: aarch64-apple-darwin20 */
/* rustc 1.85.1 (4eb161250 2025-03-15) */
/* R version: 4.6.0 */

pub const GET_REGION_BUFSIZE: u32 = 512;
