/* automatically generated by rust-bindgen 0.71.1 */

/* OS: windows */
/* Platform:  */
/* rustc 1.85.1 (4eb161250 2025-03-15) */
/* R version: 4.6.0 */

unsafe extern "C" {
    pub static mut R_num_math_threads: ::std::os::raw::c_int;
    pub static mut R_max_num_math_threads: ::std::os::raw::c_int;
}
