/* automatically generated by rust-bindgen 0.72.0 */

/* OS: windows */
/* Platform:  */
/* rustc 1.91.1 (ed61e7d7e 2025-11-07) */
/* R version: 4.5.2 */

unsafe extern "C" {
    pub static mut R_num_math_threads: ::std::os::raw::c_int;
    pub static mut R_max_num_math_threads: ::std::os::raw::c_int;
}
