/* automatically generated by rust-bindgen 0.71.1 */

/* OS: windows */
/* Platform:  */
/* rustc 1.85.1 (4eb161250 2025-03-15) */
/* R version: 4.4.3 */

unsafe extern "C" { pub fn Rprintf (arg1 : * const :: std :: os :: raw :: c_char , ...) ; pub fn REprintf (arg1 : * const :: std :: os :: raw :: c_char , ...) ; pub fn Rvprintf (arg1 : * const :: std :: os :: raw :: c_char , arg2 : va_list) ; pub fn REvprintf (arg1 : * const :: std :: os :: raw :: c_char , arg2 : va_list) ; }