/* automatically generated by rust-bindgen 0.71.1 */

/* OS: windows */
/* Platform:  */
/* rustc 1.85.1 (4eb161250 2025-03-15) */
/* R version: 4.3.3 */

unsafe extern "C" { # [doc = " S Like Memory Management"] pub fn R_chk_calloc (arg1 : usize , arg2 : usize) -> * mut :: std :: os :: raw :: c_void ; pub fn R_chk_realloc (arg1 : * mut :: std :: os :: raw :: c_void , arg2 : usize) -> * mut :: std :: os :: raw :: c_void ; pub fn R_chk_free (arg1 : * mut :: std :: os :: raw :: c_void) ; }